name: Deploy to EC2

on:
  push:
    branches: ['main', 'test/deploy'] # 배포 테스트용 브랜치 임시로 포함
  pull_request:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@9.12.3

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Job-Cracker # 프로젝트 디렉토리 경로로 수정
            git pull
            pnpm install
            pnpm build
            pm2 delete all || true  # 기존 프로세스 종료 (실패해도 계속 진행)
            pm2 start ecosystem.config.js  # PM2로 새로운 프로세스 시작
