name: Deploy to EC2

on:
  push:
    branches: ['main', 'test/deploy'] # 배포 테스트용 브랜치 임시로 포함
  pull_request:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@9.12.3

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/Job-Cracker
            git fetch --all
            git checkout ${GITHUB_REF#refs/heads/}
            git pull origin ${GITHUB_REF#refs/heads/}
            /home/ubuntu/.nvm/versions/node/v20.18.0/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v20.18.0/bin/pnpm build
            /home/ubuntu/.local/share/pnpm/pm2 delete all || true
            /home/ubuntu/.local/share/pnpm/pm2 start ecosystem.config.js
